package com.whut.dao;

import com.whut.spider.entity.ZhUser;
import org.springframework.stereotype.Repository;

public interface ZhUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_user
     *
     * @mbggenerated
     */
    int insert(ZhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_user
     *
     * @mbggenerated
     */
    int insertSelective(ZhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_user
     *
     * @mbggenerated
     */
    ZhUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZhUser record);
}