package com.whut.spider.entity;

public class ZhUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.business
     *
     * @mbggenerated
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.university
     *
     * @mbggenerated
     */
    private String university;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.major
     *
     * @mbggenerated
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.followingNum
     *
     * @mbggenerated
     */
    private String followingnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.followersNum
     *
     * @mbggenerated
     */
    private String followersnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.answerNum
     *
     * @mbggenerated
     */
    private String answernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.askNum
     *
     * @mbggenerated
     */
    private String asknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.columnNum
     *
     * @mbggenerated
     */
    private String columnnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zh_user.collectionNum
     *
     * @mbggenerated
     */
    private String collectionnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.id
     *
     * @return the value of zh_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.id
     *
     * @param id the value for zh_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.name
     *
     * @return the value of zh_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.name
     *
     * @param name the value for zh_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.sex
     *
     * @return the value of zh_user.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.sex
     *
     * @param sex the value for zh_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.business
     *
     * @return the value of zh_user.business
     *
     * @mbggenerated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.business
     *
     * @param business the value for zh_user.business
     *
     * @mbggenerated
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.company
     *
     * @return the value of zh_user.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.company
     *
     * @param company the value for zh_user.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.position
     *
     * @return the value of zh_user.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.position
     *
     * @param position the value for zh_user.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.university
     *
     * @return the value of zh_user.university
     *
     * @mbggenerated
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.university
     *
     * @param university the value for zh_user.university
     *
     * @mbggenerated
     */
    public void setUniversity(String university) {
        this.university = university == null ? null : university.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.major
     *
     * @return the value of zh_user.major
     *
     * @mbggenerated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.major
     *
     * @param major the value for zh_user.major
     *
     * @mbggenerated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.followingNum
     *
     * @return the value of zh_user.followingNum
     *
     * @mbggenerated
     */
    public String getFollowingnum() {
        return followingnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.followingNum
     *
     * @param followingnum the value for zh_user.followingNum
     *
     * @mbggenerated
     */
    public void setFollowingnum(String followingnum) {
        this.followingnum = followingnum == null ? null : followingnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.followersNum
     *
     * @return the value of zh_user.followersNum
     *
     * @mbggenerated
     */
    public String getFollowersnum() {
        return followersnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.followersNum
     *
     * @param followersnum the value for zh_user.followersNum
     *
     * @mbggenerated
     */
    public void setFollowersnum(String followersnum) {
        this.followersnum = followersnum == null ? null : followersnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.answerNum
     *
     * @return the value of zh_user.answerNum
     *
     * @mbggenerated
     */
    public String getAnswernum() {
        return answernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.answerNum
     *
     * @param answernum the value for zh_user.answerNum
     *
     * @mbggenerated
     */
    public void setAnswernum(String answernum) {
        this.answernum = answernum == null ? null : answernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.askNum
     *
     * @return the value of zh_user.askNum
     *
     * @mbggenerated
     */
    public String getAsknum() {
        return asknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.askNum
     *
     * @param asknum the value for zh_user.askNum
     *
     * @mbggenerated
     */
    public void setAsknum(String asknum) {
        this.asknum = asknum == null ? null : asknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.columnNum
     *
     * @return the value of zh_user.columnNum
     *
     * @mbggenerated
     */
    public String getColumnnum() {
        return columnnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.columnNum
     *
     * @param columnnum the value for zh_user.columnNum
     *
     * @mbggenerated
     */
    public void setColumnnum(String columnnum) {
        this.columnnum = columnnum == null ? null : columnnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zh_user.collectionNum
     *
     * @return the value of zh_user.collectionNum
     *
     * @mbggenerated
     */
    public String getCollectionnum() {
        return collectionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zh_user.collectionNum
     *
     * @param collectionnum the value for zh_user.collectionNum
     *
     * @mbggenerated
     */
    public void setCollectionnum(String collectionnum) {
        this.collectionnum = collectionnum == null ? null : collectionnum.trim();
    }
}